import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "src/styles/Home.module.css";
import { Footer } from "src/components/Footer";
import {Headline} from "src/components/Headline";
import{Main}from "src/components/Main";
import { Header } from "src/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});




// export default function About (props)({count ,isShow,handleClick,handleDisplay,text,array,handleChange,handleAdd})
 export default function About(props) {
  const{count ,isShow,handleClick,handleDisplay,text,array,handleChange,handleAdd}=props
 
  return (
    <>
      <Head>
        <title>AboutPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <button
      href="/about" 
      onClick={handleClick}>ボタン</button>
      <button onClick={handleDisplay}    >{isShow ?"非表示":"表示"}</button>


      <input type="text"  value={text} onChange={handleChange}/>
      <button onClick={handleAdd} >追加</button>
      <ul>{array.map(item=>{
        return(
          <li key={item}>{item}</li>
        )
      })}</ul>
      <Header/>
      {isShow? <h1>{count}</h1>:null}
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >  
        <Main page="about"/>
        <Footer/>
      </div>
    </>
  );
}




// import { useState, useCallback } from "react";
// import About from "./about"; // Aboutコンポーネントをインポート

// export default function Home() {
//   const [count, setCount] = useState(1);
//   const [isShow, setIsShow] = useState(false);
//   const [text, setText] = useState("");
//   const [array, setArray] = useState([]);

//   const handleClick = useCallback(() => {
//     if (count < 10) {
//       setCount(count + 1);
//     }
//   }, [count]);

//   const handleDisplay = useCallback(() => {
//     setIsShow((prevIsShow) => !prevIsShow);
//   }, []);

//   const handleChange = useCallback((e) => {
//     if (e.target.value.length > 5) {
//       alert("5文字以内にしてください");
//       return;
//     }
//     setText(e.target.value.trim());
//   }, []);

//   const handleAdd = useCallback(() => {
//     setArray((prevArray) => {
//       if (prevArray.some((item) => item === text)) {
//         alert("同じ要素がすでに存在します");
//         return prevArray;
//       }
//       return [...prevArray, text];
//     });
//   }, [text]);

//   return (
//     <div>
//       <About
//         count={count}
//         isShow={isShow}
//         handleClick={handleClick}
//         handleDisplay={handleDisplay}
//         text={text}
//         array={array}
//         handleChange={handleChange}
//         handleAdd={handleAdd}
//       />
//     </div>
//   );
// }
