import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "src/styles/Home.module.css";
import { Footer } from "src/components/Footer";
import {Headline} from "src/components/Headline";
import{Main}from "src/components/Main";
import { Header } from "src/components/Header";
import { useCallback, useEffect, useState } from "react";

// const handleClick=(e)=>{
//   console.log(e.target.href)
//   e.preventDefault();}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
//let foo=1;
 export default function Home() {
  const [count,setCount]=useState(1)
  const handleClick=(e)=>{
    setCount(count=>count+1)
    }
 
  // useEffect(()=>{
  //   document.body.style.backgroundColor="lightblue"
  //   return()=>{
  //     document.body.style.backgroundColor=""
    
  //   }

  // },[])

   useEffect(()=>{
    document.body.style.backgroundColor="lightblue"
    return()=>{
      document.body.style.backgroundColor=""
    
    }

  },[])
  console.log(count)
  return (
    <>
      <Head>
        <title>IndexPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <button
      href="/about" 
      onClick={handleClick}>ボタン</button>
      <Header/>
      <h1>{count}</h1>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Main page="index"/>
        <Footer/>
      </div>
    </>
  );
}
